name: PlotRanking
version: '${version}'
main: net.minecraftid.plotranking.PlotRanking
api-version: 1.18
authors: [ MinecraftID ]
description: Minecraft Plotsquared Ranking
website: www.minecraft-id.net
softdepend: [ PlotSquared ]
permissions:
  plotranking:
    admin:
    contest:
      register:
commands:
  PlotRanking:
    description: PlotRanking
    usage: /plotranking
    aliases: [ pr ]
  Contest:
    description: Contest
    usage: /contest
    aliases: [ ct ]